language: generic

services:
  - docker

before_install:
  - docker build --tag pydlit:latest .

script:
  - docker run -d --net=host pydlit
  - curl -XPOST -H "Content-Type: application/json" -d @example/example_request.json http://localhost:5000/api/distribute/image