language: generic

services:
  - docker

before_install:
  - docker build --tag pydlit:latest .
  -

script:
  - docker run -d -p 5000:5000 --restart=always --name registry registry:2
  - chmod u+x test.sh
  - ./test.sh
